package opencode

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/hiveryn/agentruntime"
)

const pluginTemplate = `// @managed-by-agentruntime: opencode
// @agentruntime-marker: {{.Marker}}
// Auto-generated by agentruntime. Re-install to update; direct deletion is safe.

export default {
  id: "agentruntime.opencode.{{.Marker}}",
  server: async (_input) => ({
    event: async ({ event }) => {
      try {
        const props = event.properties as any
        const sessionID = props?.sessionID ?? ""
        const parentSessionID = props?.info?.parentID ?? ""
        await fetch("{{.Endpoint}}/opencode", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            hook_event_name: event.type,
            session_id: sessionID,
            parent_session_id: parentSessionID,
            hiveryn_session_id: process.env?.HIVERYN_SESSION_ID ?? "",
            payload: props,
          }),
        })
      } catch {}
    },
    "tool.execute.before": async (inp, _out) => {
      try {
        await fetch("{{.Endpoint}}/opencode", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            hook_event_name: "tool.execute.before",
            session_id: inp.sessionID,
            parent_session_id: "",
            hiveryn_session_id: process.env?.HIVERYN_SESSION_ID ?? "",
            payload: { tool: inp.tool, callID: inp.callID },
          }),
        })
      } catch {}
    },
    "tool.execute.after": async (inp, _out) => {
      try {
        await fetch("{{.Endpoint}}/opencode", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            hook_event_name: "tool.execute.after",
            session_id: inp.sessionID,
            parent_session_id: "",
            hiveryn_session_id: process.env?.HIVERYN_SESSION_ID ?? "",
            payload: { tool: inp.tool, callID: inp.callID },
          }),
        })
      } catch {}
    },
  }),
}
`

const managedMarker = "@managed-by-agentruntime: opencode"

func (a *Adapter) EnsureSetup(_ context.Context, req agentruntime.SetupRequest) (agentruntime.SetupResult, error) {
	if !appliesTo(req.Agents, agentruntime.AgentOpenCode) {
		return agentruntime.SetupResult{}, nil
	}
	if req.Marker == "" {
		return agentruntime.SetupResult{}, fmt.Errorf("missing marker")
	}
	if req.Hook.Command == "" {
		return agentruntime.SetupResult{}, fmt.Errorf("missing hook command")
	}

	path := pluginPath(req.ConfigRoot, req.Marker)

	if data, err := os.ReadFile(path); err == nil {
		if bytes.Contains(data, []byte(managedMarker)) {
			if endpointInContent(string(data), req.Hook.Command) {
				return agentruntime.SetupResult{Changed: false, Paths: []string{path}}, nil
			}
		} else {
			return agentruntime.SetupResult{}, fmt.Errorf(
				"opencode plugin file exists but is not agentruntime-managed; refusing to overwrite: %s", path)
		}
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return agentruntime.SetupResult{}, fmt.Errorf("opencode mkdir: %w", err)
	}

	content, err := renderPlugin(req.Hook.Command, req.Marker)
	if err != nil {
		return agentruntime.SetupResult{}, err
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return agentruntime.SetupResult{}, fmt.Errorf("opencode write plugin: %w", err)
	}

	return agentruntime.SetupResult{Changed: true, Paths: []string{path}}, nil
}

func (a *Adapter) RemoveSetup(_ context.Context, req agentruntime.SetupRequest) (agentruntime.SetupResult, error) {
	if !appliesTo(req.Agents, agentruntime.AgentOpenCode) {
		return agentruntime.SetupResult{}, nil
	}
	if req.Marker == "" {
		return agentruntime.SetupResult{}, fmt.Errorf("missing marker")
	}

	path := pluginPath(req.ConfigRoot, req.Marker)

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return agentruntime.SetupResult{Changed: false, Paths: []string{path}}, nil
		}
		return agentruntime.SetupResult{}, fmt.Errorf("opencode read plugin: %w", err)
	}

	if !bytes.Contains(data, []byte(managedMarker)) {
		return agentruntime.SetupResult{}, fmt.Errorf(
			"opencode plugin file at %s is not agentruntime-managed; refusing to remove", path)
	}

	markerLine := "@agentruntime-marker: " + req.Marker
	if !bytes.Contains(data, []byte(markerLine)) {
		return agentruntime.SetupResult{Changed: false, Paths: []string{path}}, nil
	}

	if err := os.Remove(path); err != nil {
		return agentruntime.SetupResult{}, fmt.Errorf("opencode remove plugin: %w", err)
	}

	return agentruntime.SetupResult{Changed: true, Paths: []string{path}}, nil
}

func pluginPath(configRoot, marker string) string {
	filename := "agentruntime-" + marker + ".ts"
	if configRoot != "" {
		return filepath.Join(configRoot, ".config", "opencode", "plugins", filename)
	}
	return filepath.Join(userConfigDir(), "opencode", "plugins", filename)
}

// userConfigDir resolves the XDG-compliant user config base directory.
// It intentionally does NOT use os.UserConfigDir() because that returns
// ~/Library/Application Support on macOS, which is not where OpenCode looks.
func userConfigDir() string {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return xdg
	}
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return ""
	}
	return filepath.Join(home, ".config")
}

func renderPlugin(endpoint, marker string) (string, error) {
	tmpl, err := template.New("plugin").Parse(pluginTemplate)
	if err != nil {
		return "", fmt.Errorf("opencode plugin template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, map[string]string{
		"Endpoint": endpoint,
		"Marker":   marker,
	}); err != nil {
		return "", fmt.Errorf("opencode plugin render: %w", err)
	}
	return buf.String(), nil
}

// endpointInContent checks whether the endpoint URL appears in the plugin file.
// The plugin posts to <endpoint>/opencode.
func endpointInContent(content, endpoint string) bool {
	return strings.Contains(content, endpoint+"/opencode")
}

func appliesTo(agents []agentruntime.AgentKind, target agentruntime.AgentKind) bool {
	if len(agents) == 0 {
		return true
	}
	for _, a := range agents {
		if a == target {
			return true
		}
	}
	return false
}
